version: '3.7'
services:
 dev-api:
  build:
   context: .
   dockerfile: Dockerfile-dev
  working_dir: /src
  volumes:
   - .:/src
   - ./docker-compose/dev-certificates/root-ca.pem:/euler/root-ca.pem:ro
  user: ${CURRENT_UID}:${CURRENT_GID}
  environment:
   - LANG=C.UTF-8
   - LC_ALL=C.UTF-8
  ports:
   - 8000:8000
  depends_on:
   - elastic-dev
  command: /src/docker-compose/entrypoint.sh
 elastic-dev:
  image: elasticsearch:8.8.0
  environment:
    - "xpack.security.enabled=false"
    - "discovery.type=single-node"
    - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
  volumes:
   - es-data:/usr/share/elasticsearch/data
  ports:
   - 9200:9200
   - 9300:9300

 kibana-dev:
  image: kibana:8.8.0
  ports:
   - 5601:5601
  environment:
   ELASTICSEARCH_URL: http://elastic-dev:9200
   ELASTICSEARCH_HOSTS: http://elastic-dev:9200
  depends_on:
   - elastic-dev

volumes:
 es-data:
